input {
  tcp {
    port => 5000
    codec => json
  }

  gelf {
    port => 12201
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "cafeteria-backend" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cafeteria-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
